import "https://esm.sh/@supabase/functions-js/src/edge-runtime.d.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const supabase = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        )

        const { query, context, user_id } = await req.json()

        if (!query) {
            return new Response(
                JSON.stringify({ error: 'Query is required' }),
                { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
            )
        }

        let systemContext = "";
        if (user_id) {
            const { data: profile } = await supabase
                .from('profiles')
                .select('learning_goals, learning_style')
                .eq('id', user_id)
                .single();

            if (profile) {
                const goals = profile.learning_goals?.join(", ") || "General learning";
                const style = profile.learning_style || "General";
                systemContext = `
                User Profile:
                - Learning Style: ${style}
                - Learning Goals: ${goals}
                
                Instruction: Adapt your teaching style to match the user's preference. 
                - If 'Visual', use vivid descriptions, ask them to visualize concepts, or describe diagrams.
                - If 'Auditory', use conversational language and explain as if speaking.
                - If 'Reading/Writing', provide clear, structured text with lists and definitions.
                - If 'Kinesthetic', suggest practical exercises, real-world examples, or "try this" activities.
                - Focus on helping them achieve their goals: ${goals}.
                `;
            }
        }

        const prompt = `
      You are a helpful AI study assistant.
      ${systemContext}

      Use the following context (documents uploaded by the user) to answer the user's question.
      If the answer is not in the context, say you don't know based on the documents, but try to help with general knowledge if appropriate (but mention it's general knowledge).
      
      Context:
      ${context || "No documents selected."}
      
      User Question:
      ${query}
    `;

        const geminiResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${Deno.env.get('GEMINI_API_KEY')}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: prompt }]
                }]
            }),
        })

        const aiData = await geminiResponse.json()

        if (aiData.error) {
            console.error("Gemini API Error:", aiData.error);
            throw new Error(aiData.error.message)
        }

        if (!aiData.candidates || aiData.candidates.length === 0) {
            console.error("No candidates returned:", aiData);
            throw new Error("No response generated by AI. It might have been blocked by safety filters.");
        }

        const candidate = aiData.candidates[0];
        if (!candidate.content || !candidate.content.parts || candidate.content.parts.length === 0) {
            console.error("Invalid candidate structure:", candidate);
            throw new Error("Invalid response structure from AI.");
        }

        const reply = candidate.content.parts[0].text

        return new Response(
            JSON.stringify({
                reply: reply
            }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        )

    } catch (error) {
        return new Response(
            JSON.stringify({ error: error.message }),
            { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
        )
    }
})
